site_name: pinax-cms
pages:
- [index.md, Home]
- [changelog.md, Change Log]
theme: readthedocs
repo_url: https://github.com/pinax/pinax-cms
site_description: "an lightweight CMS app for Django projects born out of Symposion"
site_author: "Pinax Team"
markdown_extensions: [admonition]
